site_name: pentest
locale: fi
theme: jekyll-theme-hacker
markdown: kramdown
site_url: https://nihti.github.io/pentest/
site_author: Niko Lehtiniemi
site_description: Haaga-Helian tunkeutumistestaus-kurssi ICT4TN027-3008 syksy 2021
nav: 
  - Index: 'index.md'
  - Joko tai: 'start.md'
  - h1: 'h1.md'
  - h2: 'h2.md'
  - h3: 'h3.md'
  - h4: 'h4.md'
  - Lounas: 'lunch.md'
  - SharkSoup: 'sharksoup.md'
  - Page documentation: 'page-doc.md'
