site_name: pentest
theme: jekyll-theme-hacker
markdown: kramdown
site_url: https://nihti.github.io/pentest/
site_author: Niko Lehtiniemi
site_description: Haaga-Helian tunkeutumistestaus-kurssi ICT4TN027-3008 syksy 2021
nav: 
  - 'index.md'
  - 'about.md'
